version: '3.8'

networks:
  coolify:
    external: true

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  symfony_vendor:
  symfony_var:
  gitea_data:

services:
  # ======================
  # BASE DE DONNÉES (INCHANGÉ)
  # ======================
  postgres:
    image: 'postgres:15-alpine'
    container_name: maestro-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - './scripts/init:/docker-entrypoint-initdb.d:ro'
    networks:
      - coolify
    ports:
      - '5432:5432'
    mem_limit: 1g
    mem_reservation: 512m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ======================
  # CACHE REDIS (INCHANGÉ)
  # ======================
  redis:
    image: 'redis:7-alpine'
    container_name: maestro-cache
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 60 1
      --appendonly no
    volumes:
      - 'redis_data:/data'
    networks:
      - coolify
    expose:
      - 6379
    mem_limit: 384m
    mem_reservation: 256m
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # ======================
  # ORCHESTRATEUR N8N (INCHANGÉ)
  # ======================
  n8n:
    image: 'n8nio/n8n:latest'
    container_name: maestro-n8n
    restart: unless-stopped
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: '${N8N_BASIC_AUTH_USER}'
      N8N_BASIC_AUTH_PASSWORD: '${N8N_BASIC_AUTH_PASSWORD}'
      N8N_ENCRYPTION_KEY: '${N8N_ENCRYPTION_KEY}'
      N8N_HOST: 'n8n.maestro.ara-solutions.cloud'
      N8N_PORT: '5678'
      N8N_PROTOCOL: 'https'
      WEBHOOK_URL: 'https://n8n.maestro.ara-solutions.cloud'
      DB_TYPE: 'postgresdb'
      DB_POSTGRESDB_HOST: 'postgres'
      DB_POSTGRESDB_PORT: '5432'
      DB_POSTGRESDB_DATABASE: 'n8n'
      DB_POSTGRESDB_USER: '${POSTGRES_USER}'
      DB_POSTGRESDB_PASSWORD: '${POSTGRES_PASSWORD}'
      EXECUTIONS_PROCESS: 'main'
      GENERIC_TIMEZONE: 'Europe/Paris'
      N8N_METRICS: 'false'
      N8N_VERSION_NOTIFICATIONS_ENABLED: 'false'
    volumes:
      - 'n8n_data:/home/node/.n8n'
      - './workflows:/home/node/workflows'
    networks:
      - coolify
    expose:
      - 5678
    mem_limit: 1g
    mem_reservation: 512m
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.maestro.ara-solutions.cloud`)"
      - "traefik.http.routers.n8n.entrypoints=https"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  # ======================
  # APPLICATION SYMFONY PHP 8.2
  # ======================
  symfony:
    image: 'dunglas/frankenphp:latest-php8.2'
    container_name: maestro-symfony
    restart: unless-stopped
    environment:
      SERVER_NAME: 'maestro.ara-solutions.cloud'
      FRANKENPHP_CONFIG: |
        {
          order php_server before file_server
        }
        
        maestro.ara-solutions.cloud {
          root * /app/public
          
          php_server {
            index index.php
          }
          
          encode zstd gzip
          file_server
        }
      
      # Symfony environment
      APP_ENV: '${APP_ENV:-prod}'
      APP_SECRET: '${APP_SECRET}'
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?serverVersion=15&charset=utf8'
      
      # Redis for cache
      REDIS_URL: 'redis://:${REDIS_PASSWORD}@redis:6379'
      
      # n8n webhook
      N8N_WEBHOOK_URL: 'http://n8n:5678/webhook'
      
      # API Keys
      GEMINI_API_KEY: '${GEMINI_API_KEY}'
      
      # PHP Configuration
      PHP_MEMORY_LIMIT: '256M'
      PHP_UPLOAD_MAX_FILESIZE: '32M'
      PHP_POST_MAX_SIZE: '32M'
      
    volumes:
      - './symfony-app:/app'
      - 'symfony_vendor:/app/vendor'
      - 'symfony_var:/app/var'
    networks:
      - coolify
    ports:
      - '8080:80'
      - '443:443'
    mem_limit: 1g
    mem_reservation: 512m
    depends_on:
      - postgres
      - redis
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maestro.rule=Host(`maestro.ara-solutions.cloud`)"
      - "traefik.http.routers.maestro.entrypoints=https"
      - "traefik.http.routers.maestro.tls=true"
      - "traefik.http.routers.maestro.tls.certresolver=letsencrypt"
      - "traefik.http.services.maestro.loadbalancer.server.port=80"

  # ======================
  # GITEA - GIT SERVER
  # ======================
  gitea:
    image: 'gitea/gitea:1.21'
    container_name: maestro-gitea
    restart: unless-stopped
    environment:
      USER_UID: '1000'
      USER_GID: '1000'
      GITEA__database__DB_TYPE: 'postgres'
      GITEA__database__HOST: 'postgres:5432'
      GITEA__database__NAME: 'gitea'
      GITEA__database__USER: '${POSTGRES_USER}'
      GITEA__database__PASSWD: '${POSTGRES_PASSWORD}'
      GITEA__server__ROOT_URL: 'https://git.maestro.ara-solutions.cloud/'
      GITEA__server__HTTP_PORT: '3000'
      GITEA__server__DOMAIN: 'git.maestro.ara-solutions.cloud'
      GITEA__server__SSH_PORT: '2222'
      GITEA__server__SSH_DOMAIN: 'git.maestro.ara-solutions.cloud'
      GITEA__service__DISABLE_REGISTRATION: 'true'
      GITEA__api__ENABLE_SWAGGER: 'true'
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
      GITEA__database__SCHEMA: 'public'
    volumes:
      - 'gitea_data:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - coolify
    ports:
      - '3000:3000'
      - '2222:22'
    mem_limit: 768m
    mem_reservation: 512m
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.maestro.ara-solutions.cloud`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"